fix: error message

diff --git a/.github/workflows/convert-pr-to-draft.yml b/.github/workflows/convert-pr-to-draft.yml
--- a/.github/workflows/convert-pr-to-draft.yml
+++ b/.github/workflows/convert-pr-to-draft.yml
@@ -15,4 +15,7 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          gh pr ready --undo ${{ github.event.pull_request.number }} --repo ${{ github.repository }}
+          gh pr ready --undo ${{ github.event.pull_request.number }} --repo ${{ github.repository }} || {
+            echo "Warning: Failed to auto-convert PR to draft. Please manually mark as draft if needed." 
+            exit 0; 
+          }
